using Oproto.FluentDynamoDb.SourceGenerator.Models;
using System.Text;

namespace Oproto.FluentDynamoDb.SourceGenerator.Generators;

/// <summary>
/// Generates static field name constant classes for DynamoDB entities.
/// </summary>
internal static class FieldsGenerator
{
    /// <summary>
    /// Generates a static Fields class containing field name constants for the entity.
    /// </summary>
    /// <param name="entity">The entity model to generate fields for.</param>
    /// <returns>The generated C# source code.</returns>
    public static string GenerateFieldsClass(EntityModel entity)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This code was generated by the DynamoDB Source Generator.");
        sb.AppendLine("// Changes to this file may be lost when the code is regenerated.");
        sb.AppendLine();
        sb.AppendLine($"namespace {entity.Namespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Field name constants for {entity.ClassName} DynamoDB attributes.");
        sb.AppendLine($"    /// These constants provide compile-time safety when referencing DynamoDB attribute names");
        sb.AppendLine($"    /// in queries, expressions, and other operations.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    /// <remarks>");
        sb.AppendLine($"    /// Generated from entity: {entity.ClassName}");
        sb.AppendLine($"    /// Target table: {entity.TableName}");
        sb.AppendLine($"    /// Generated on: {DateTimeOffset.UtcNow:yyyy-MM-dd HH:mm:ss UTC}");
        sb.AppendLine($"    /// </remarks>");
        sb.AppendLine($"    public static partial class {entity.ClassName}Fields");
        sb.AppendLine("    {");

        // Generate main field constants
        GenerateMainFieldConstants(sb, entity);

        // Generate GSI field classes
        GenerateGsiFieldClasses(sb, entity);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the main field constants for entity properties.
    /// </summary>
    private static void GenerateMainFieldConstants(StringBuilder sb, EntityModel entity)
    {
        var propertiesWithAttributes = entity.Properties
            .Where(p => p.HasAttributeMapping)
            .OrderBy(p => p.PropertyName)
            .ToArray();

        if (propertiesWithAttributes.Length == 0)
            return;

        foreach (var property in propertiesWithAttributes)
        {
            var fieldName = GetSafeFieldName(property.PropertyName);
            var attributeName = property.AttributeName;

            sb.AppendLine($"        /// <summary>");
            sb.AppendLine($"        /// DynamoDB attribute name for {property.PropertyName} property.");
            sb.AppendLine($"        /// </summary>");
            sb.AppendLine($"        public const string {fieldName} = \"{attributeName}\";");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Generates nested GSI field classes for Global Secondary Index attributes.
    /// </summary>
    private static void GenerateGsiFieldClasses(StringBuilder sb, EntityModel entity)
    {
        if (entity.Indexes.Length == 0)
            return;

        foreach (var index in entity.Indexes.OrderBy(i => i.IndexName))
        {
            GenerateGsiFieldClass(sb, entity, index);
        }
    }

    /// <summary>
    /// Generates a nested field class for a specific GSI.
    /// </summary>
    private static void GenerateGsiFieldClass(StringBuilder sb, EntityModel entity, IndexModel index)
    {
        var className = GetSafeClassName($"{index.IndexName}Fields");

        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Field name constants for {index.IndexName} Global Secondary Index.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static partial class {className}");
        sb.AppendLine("        {");

        // Generate partition key field
        var partitionKeyProperty = entity.Properties.FirstOrDefault(p => p.PropertyName == index.PartitionKeyProperty);
        if (partitionKeyProperty != null)
        {
            var fieldName = GetSafeFieldName("PartitionKey");
            sb.AppendLine($"            /// <summary>");
            sb.AppendLine($"            /// Partition key attribute name for {index.IndexName} GSI.");
            sb.AppendLine($"            /// </summary>");
            sb.AppendLine($"            public const string {fieldName} = \"{partitionKeyProperty.AttributeName}\";");
            sb.AppendLine();
        }

        // Generate sort key field if exists
        if (!string.IsNullOrEmpty(index.SortKeyProperty))
        {
            var sortKeyProperty = entity.Properties.FirstOrDefault(p => p.PropertyName == index.SortKeyProperty);
            if (sortKeyProperty != null)
            {
                var fieldName = GetSafeFieldName("SortKey");
                sb.AppendLine($"            /// <summary>");
                sb.AppendLine($"            /// Sort key attribute name for {index.IndexName} GSI.");
                sb.AppendLine($"            /// </summary>");
                sb.AppendLine($"            public const string {fieldName} = \"{sortKeyProperty.AttributeName}\";");
                sb.AppendLine();
            }
        }

        // Generate projected field constants for properties that are part of this GSI
        GenerateGsiProjectedFields(sb, entity, index);

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    /// <summary>
    /// Generates field constants for properties projected in a GSI.
    /// </summary>
    private static void GenerateGsiProjectedFields(StringBuilder sb, EntityModel entity, IndexModel index)
    {
        // Find all properties that have GSI attributes for this index (excluding key properties already handled)
        var projectedProperties = entity.Properties
            .Where(p => p.GlobalSecondaryIndexes.Any(gsi => gsi.IndexName == index.IndexName) &&
                       p.PropertyName != index.PartitionKeyProperty &&
                       p.PropertyName != index.SortKeyProperty &&
                       p.HasAttributeMapping)
            .OrderBy(p => p.PropertyName)
            .ToArray();

        foreach (var property in projectedProperties)
        {
            var fieldName = GetSafeFieldName(property.PropertyName);
            sb.AppendLine($"            /// <summary>");
            sb.AppendLine($"            /// DynamoDB attribute name for {property.PropertyName} property in {index.IndexName} GSI.");
            sb.AppendLine($"            /// </summary>");
            sb.AppendLine($"            public const string {fieldName} = \"{property.AttributeName}\";");
            sb.AppendLine();
        }
    }

    /// <summary>
    /// Converts a property name to a safe field name, handling reserved words and special cases.
    /// </summary>
    private static string GetSafeFieldName(string propertyName)
    {
        // Handle reserved C# keywords by prefixing with @
        var csharpReservedWords = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
            "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
            "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
            "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
            "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
            "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
            "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this",
            "throw", "true", "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort",
            "using", "virtual", "void", "volatile", "while"
        };

        // DynamoDB reserved words that should also be escaped for clarity
        var dynamoDbReservedWords = new HashSet<string>(StringComparer.Ordinal)
        {
            "ABORT", "ABSOLUTE", "ACTION", "ADD", "AFTER", "AGENT", "AGGREGATE", "ALL", "ALLOCATE", "ALTER",
            "ANALYZE", "AND", "ANY", "ARCHIVE", "ARE", "ARRAY", "AS", "ASC", "ASCII", "ASENSITIVE",
            "ASSERTION", "ASYMMETRIC", "AT", "ATOMIC", "ATTACH", "ATTRIBUTE", "AUTH", "AUTHORIZATION", "AUTHORIZE", "AUTO",
            "AVG", "BACK", "BACKUP", "BASE", "BATCH", "BEFORE", "BEGIN", "BETWEEN", "BIGINT", "BINARY",
            "BIT", "BLOB", "BLOCK", "BOOLEAN", "BOTH", "BREADTH", "BUCKET", "BULK", "BY", "BYTE",
            "CALL", "CALLED", "CALLING", "CAPACITY", "CASCADE", "CASCADED", "CASE", "CAST", "CATALOG", "CHAR",
            "CHARACTER", "CHECK", "CLASS", "CLOB", "CLOSE", "CLUSTER", "CLUSTERED", "CLUSTERING", "CLUSTERS", "COALESCE",
            "COLLATE", "COLLATION", "COLLECTION", "COLUMN", "COLUMNS", "COMBINE", "COMMENT", "COMMIT", "COMPACT", "COMPILE",
            "COMPRESS", "CONDITION", "CONFLICT", "CONNECT", "CONNECTION", "CONSISTENCY", "CONSISTENT", "CONSTRAINT", "CONSTRAINTS", "CONSTRUCTOR",
            "CONSUMED", "CONTINUE", "CONVERT", "COPY", "CORRESPONDING", "COUNT", "COUNTER", "CREATE", "CROSS", "CUBE",
            "CURRENT", "CURSOR", "CYCLE", "DATA", "DATABASE", "DATE", "DATETIME", "DAY", "DEALLOCATE", "DEC",
            "DECIMAL", "DECLARE", "DEFAULT", "DEFERRABLE", "DEFERRED", "DEFINE", "DEFINED", "DEFINITION", "DELETE", "DELIMITED",
            "DEPTH", "DEREF", "DESC", "DESCRIBE", "DESCRIPTOR", "DETACH", "DETERMINISTIC", "DIAGNOSTICS", "DIRECTORIES", "DISABLE",
            "DISCONNECT", "DISTINCT", "DISTRIBUTE", "DO", "DOMAIN", "DOUBLE", "DROP", "DUMP", "DURATION", "DYNAMIC",
            "EACH", "ELEMENT", "ELSE", "ELSEIF", "EMPTY", "ENABLE", "END", "EQUAL", "EQUALS", "ERROR",
            "ESCAPE", "ESCAPED", "EVAL", "EVALUATE", "EXCEEDED", "EXCEPT", "EXCEPTION", "EXCEPTIONS", "EXCLUSIVE", "EXEC",
            "EXECUTE", "EXISTS", "EXIT", "EXPLAIN", "EXPLODE", "EXPORT", "EXPRESSION", "EXTENDED", "EXTERNAL", "EXTRACT",
            "FAIL", "FALSE", "FAMILY", "FETCH", "FIELDS", "FILE", "FILTER", "FILTERING", "FINAL", "FINISH",
            "FIRST", "FIXED", "FLATTERN", "FLOAT", "FOR", "FORCE", "FOREIGN", "FORMAT", "FORWARD", "FOUND",
            "FREE", "FROM", "FULL", "FUNCTION", "FUNCTIONS", "GENERAL", "GENERATE", "GET", "GLOB", "GLOBAL",
            "GO", "GOTO", "GRANT", "GREATER", "GROUP", "GROUPING", "HANDLER", "HASH", "HAVE", "HAVING",
            "HEAP", "HIDDEN", "HOLD", "HOUR", "IDENTIFIED", "IDENTITY", "IF", "IGNORE", "IMMEDIATE", "IMPORT",
            "IN", "INCLUDING", "INCLUSIVE", "INCREMENT", "INCREMENTAL", "INDEX", "INDEXED", "INDEXES", "INDICATOR", "INFINITE",
            "INITIALLY", "INLINE", "INNER", "INNTER", "INOUT", "INPUT", "INSENSITIVE", "INSERT", "INSTEAD", "INT",
            "INTEGER", "INTERSECT", "INTERVAL", "INTO", "INVALIDATE", "IS", "ISOLATION", "ITEM", "ITEMS", "ITERATE",
            "JOIN", "KEY", "KEYS", "LAG", "LANGUAGE", "LARGE", "LAST", "LATERAL", "LEAD", "LEADING",
            "LEAVE", "LEFT", "LENGTH", "LESS", "LEVEL", "LIKE", "LIMIT", "LIMITED", "LINES", "LIST",
            "LOAD", "LOCAL", "LOCALTIME", "LOCALTIMESTAMP", "LOCATION", "LOCATOR", "LOCK", "LOCKS", "LOG", "LOGED",
            "LONG", "LOOP", "LOWER", "MAP", "MATCH", "MATERIALIZED", "MAX", "MAXLEN", "MEMBER", "MERGE",
            "METHOD", "METRICS", "MIN", "MINUS", "MINUTE", "MISSING", "MOD", "MODE", "MODIFIES", "MODIFY",
            "MODULE", "MONTH", "MULTI", "MULTISET", "NAME", "NAMES", "NATIONAL", "NATURAL", "NCHAR", "NCLOB",
            "NEW", "NEXT", "NO", "NONE", "NOT", "NULL", "NULLIF", "NUMBER", "NUMERIC", "OBJECT",
            "OF", "OFFLINE", "OFFSET", "OLD", "ON", "ONLINE", "ONLY", "OPAQUE", "OPEN", "OPERATOR",
            "OPTION", "OR", "ORDER", "ORDINALITY", "OTHER", "OTHERS", "OUT", "OUTER", "OUTPUT", "OVER",
            "OVERLAPS", "OVERRIDE", "OWNER", "PAD", "PARALLEL", "PARAMETER", "PARAMETERS", "PARTIAL", "PARTITION", "PARTITIONED",
            "PARTITIONS", "PATH", "PERCENT", "PERCENTILE", "PERMISSION", "PERMISSIONS", "PIPE", "PIPELINED", "PLAN", "POOL",
            "POSITION", "PRECISION", "PREPARE", "PRESERVE", "PRIMARY", "PRIOR", "PRIVATE", "PRIVILEGES", "PROCEDURE", "PROCESSED",
            "PROJECT", "PROJECTION", "PROPERTY", "PROVISIONING", "PUBLIC", "PUT", "QUERY", "QUIT", "QUORUM", "RAISE",
            "RANDOM", "RANGE", "RANK", "RAW", "READ", "READS", "REAL", "REBUILD", "RECORD", "RECURSIVE",
            "REDUCE", "REF", "REFERENCE", "REFERENCES", "REFERENCING", "REGEXP", "REGION", "REINDEX", "RELATIVE", "RELEASE",
            "REMAINDER", "RENAME", "REPEAT", "REPLACE", "REQUEST", "RESET", "RESIGNAL", "RESOURCE", "RESPONSE", "RESTORE",
            "RESTRICT", "RESULT", "RETURN", "RETURNING", "RETURNS", "REVERSE", "REVOKE", "RIGHT", "ROLE", "ROLES",
            "ROLLBACK", "ROLLUP", "ROUTINE", "ROW", "ROWS", "RULE", "RULES", "SAMPLE", "SATISFIES", "SAVE",
            "SAVEPOINT", "SCAN", "SCHEMA", "SCOPE", "SCROLL", "SEARCH", "SECOND", "SECTION", "SEGMENT", "SEGMENTS",
            "SELECT", "SELF", "SEMI", "SENSITIVE", "SEPARATE", "SEQUENCE", "SERIALIZABLE", "SESSION", "SET", "SETS",
            "SHARD", "SHARE", "SHARED", "SHORT", "SHOW", "SIGNAL", "SIMILAR", "SIZE", "SKEWED", "SMALLINT",
            "SNAPSHOT", "SOME", "SOURCE", "SPACE", "SPACES", "SPARSE", "SPECIFIC", "SPECIFICTYPE", "SPLIT", "SQL",
            "SQLCODE", "SQLERROR", "SQLEXCEPTION", "SQLSTATE", "SQLWARNING", "START", "STATE", "STATIC", "STATUS", "STORAGE",
            "STORE", "STORED", "STREAM", "STRING", "STRUCT", "STYLE", "SUB", "SUBMULTISET", "SUBPARTITION", "SUBSTRING",
            "SUBTYPE", "SUM", "SUPER", "SYMMETRIC", "SYNONYM", "SYSTEM", "TABLE", "TABLESAMPLE", "TEMP", "TEMPORARY",
            "TERMINATED", "TEXT", "THAN", "THEN", "THROUGHPUT", "TIME", "TIMESTAMP", "TIMEZONE", "TINYINT", "TO",
            "TOKEN", "TOTAL", "TOUCH", "TRAILING", "TRANSACTION", "TRANSFORM", "TRANSLATE", "TRANSLATION", "TREAT", "TRIGGER",
            "TRIM", "TRUE", "TRUNCATE", "TTL", "TUPLE", "TYPE", "UNDER", "UNDO", "UNION", "UNIQUE",
            "UNIT", "UNKNOWN", "UNLOGGED", "UNNEST", "UNPROCESSED", "UNSIGNED", "UNTIL", "UPDATE", "UPPER", "URL",
            "USAGE", "USE", "USER", "USERS", "USING", "UUID", "VACUUM", "VALUE", "VALUED", "VALUES",
            "VARCHAR", "VARIABLE", "VARIANCE", "VARINT", "VARYING", "VIEW", "VIEWS", "VIRTUAL", "VOID", "WAIT",
            "WHEN", "WHENEVER", "WHERE", "WHILE", "WINDOW", "WITH", "WITHIN", "WITHOUT", "WORK", "WRAPPED",
            "WRITE", "YEAR", "ZONE"
        };

        // Escape both C# and DynamoDB reserved words
        if (csharpReservedWords.Contains(propertyName) || dynamoDbReservedWords.Contains(propertyName))
        {
            return $"@{propertyName}";
        }

        // Ensure the field name starts with a letter or underscore
        if (!char.IsLetter(propertyName[0]) && propertyName[0] != '_')
        {
            return $"_{propertyName}";
        }

        return propertyName;
    }

    /// <summary>
    /// Converts an index name to a safe class name.
    /// </summary>
    private static string GetSafeClassName(string indexName)
    {
        // Remove invalid characters and ensure it starts with a letter or underscore
        var safeName = new StringBuilder();

        for (int i = 0; i < indexName.Length; i++)
        {
            char c = indexName[i];

            if (i == 0)
            {
                // First character must be letter or underscore
                if (char.IsLetter(c) || c == '_')
                {
                    safeName.Append(c);
                }
                else if (char.IsDigit(c))
                {
                    safeName.Append('_').Append(c);
                }
                else
                {
                    safeName.Append('_');
                }
            }
            else
            {
                // Subsequent characters can be letters, digits, or underscores
                if (char.IsLetterOrDigit(c) || c == '_')
                {
                    safeName.Append(c);
                }
                else
                {
                    safeName.Append('_');
                }
            }
        }

        var result = safeName.ToString();

        // Ensure we don't have an empty result
        if (string.IsNullOrEmpty(result))
        {
            result = "_Index";
        }

        return result;
    }
}